// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/atmxlab/vpn/internal/client/handlers/tunnel (interfaces: Signaller)
//
// Generated by this command:
//
//	mockgen -destination=/Users/timur_abdurashidov/Desktop/other/vpn/internal/client/handlers/tunnel/mocks/Signaller_mock.go -package=mocks . Signaller
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSignaller is a mock of Signaller interface.
type MockSignaller struct {
	ctrl     *gomock.Controller
	recorder *MockSignallerMockRecorder
}

// MockSignallerMockRecorder is the mock recorder for MockSignaller.
type MockSignallerMockRecorder struct {
	mock *MockSignaller
}

// NewMockSignaller creates a new mock instance.
func NewMockSignaller(ctrl *gomock.Controller) *MockSignaller {
	mock := &MockSignaller{ctrl: ctrl}
	mock.recorder = &MockSignallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignaller) EXPECT() *MockSignallerMockRecorder {
	return m.recorder
}

// Signal mocks base method.
func (m *MockSignaller) Signal(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signal indicates an expected call of Signal.
func (mr *MockSignallerMockRecorder) Signal(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockSignaller)(nil).Signal), arg0)
}
