// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/atmxlab/vpn/internal/client (interfaces: SynAction)
//
// Generated by this command:
//
//	mockgen -destination=/Users/timur_abdurashidov/Desktop/other/vpn/internal/client/mocks/SynAction_mock.go -package=mocks . SynAction
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSynAction is a mock of SynAction interface.
type MockSynAction struct {
	ctrl     *gomock.Controller
	recorder *MockSynActionMockRecorder
}

// MockSynActionMockRecorder is the mock recorder for MockSynAction.
type MockSynActionMockRecorder struct {
	mock *MockSynAction
}

// NewMockSynAction creates a new mock instance.
func NewMockSynAction(ctrl *gomock.Controller) *MockSynAction {
	mock := &MockSynAction{ctrl: ctrl}
	mock.recorder = &MockSynActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSynAction) EXPECT() *MockSynActionMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockSynAction) Run(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockSynActionMockRecorder) Run(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSynAction)(nil).Run), arg0)
}
